version: '2'
services:
  web:
    build: .
    container_name: flask_web_app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
  redis:
    image: redis
    container_name: redis_instance
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
  postgres:
    image: postgres:latest
    container_name: postgres_instance
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data