version: '2'
services:
  web:
    build: .
    container_name: flask_web_app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis_instance
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]