version: '2'
services:
  web:
    build: .
    container_name: flask_web_app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_instance
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data